### ISSUE TITLE
Create a version of this project in Python

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/redisbloom-moby-dick#1]
Create a version of this project written in Python using the [redis-py](https://github.com/redis/redis-py) Redis client.  Your code should live in a new folder named `python` which should also contain a `requirements.txt` and `README.md` that tells people how to install dependencies and run the code.

You'll want to leave the input data file `moby_dick_just_words.txt` where it is and point to it in your data loading code.  You'll also want to move the existing Node.js project files: `.nvmrc`, `package.json`, `package-lock.json` and `index.js` into their own folder called `nodejs`, adding a `README.md` in there that tells people how to set up and use the Node code (use the text in the existing repo `README.md` file).

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by divyansh-ag-03** [comment]
Hi  @simonprickett @SuzeShardlow I am new to open source with Hacktoberfest. I am well versed in Python and Java. Please let me know which project is to be converted to python and what all are your requirements other than the ones mentioned above.
Kindly assign the work to me.

**Comment by SuzeShardlow** [comment]
Hi @divyansh-ag-03, thanks for your interest and welcome to Hacktoberfest :)  The project is this one, which is written in JavaScript

https://github.com/redis-developer/redisbloom-moby-dick

and we are looking for someone to create the same project in Python.

Does that make sense?

I will wait for you to confirm you're comfortable with this before I assign it to you.

**Comment by SuzeShardlow** [comment]
This issue is still up for grabs :) please comment and tag me and @simonprickett if you'd like to work on it.

**Comment by radioactive11** [comment]
@SuzeShardlow @simonprickett May I please work on this issue. I went through the JS Repo and I am confident I will be able to make a Python version of the same.

**Comment by SuzeShardlow** [comment]
Hi @radioactive11, I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/

**Comment by radioactive11** [comment]
Thank you @SuzeShardlow for assigning this issue. I will start working on this right away 😃

**Comment by SuzeShardlow** [comment]
Cool, have fun 🙌🏽
